config/routes.rb
SampleApp::Application.routes.draw do

  resources :sample_users do
    member do
      get :following, :followers
    end
  end
    
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy] 

  root to: 'static_pages#home'

  match '/help', to: 'static_pages#help'

  match '/about', to: 'static_pages#about'

  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'sample_users#new'

  match '/signin', to: 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://mindin1.com/">TwinPets.com</a>
		Twitter Alike Demo
	</small>
	<nav>
		<ul>
			<li><%= link_to "About Us", about_path %></li>
			<li><%= link_to "Contact Us", contact_path %></li>
			<li><a href="http://railstutorial.org/">ruby on rails tutorials contributed by Michael Hartl</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("/assets/twinpets_log.png", height: 32, width: 32), 'http://mindin1.com', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "All Users", sample_users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_sample_user.name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_sample_user %></li>
                <li><%= link_to "Settings", edit_sample_user_path(current_sample_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign Out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |key, value| %>
        	<%= content_tag(:div, value, class: "alert alert-#{key}") %>
      	<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>